all:ser1 ser2 ser3


ser1:ser1.cpp ser.cpp conn.cpp 
	g++ -o ser1 ser1.cpp ser.cpp conn.cpp

ser2:ser2.cpp ser.cpp conn.cpp 
	g++ -o ser2 ser2.cpp ser.cpp conn.cpp
ser3:ser3.cpp ser.cpp conn.cpp 
	g++ -o ser3 ser3.cpp ser.cpp conn.cpp

